apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-cicd-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-cicd-staging
  template:
    metadata:
      labels:
        app: simple-cicd-staging
    spec:
      containers:
        - name: simple-cicd-staging
          image: rknoplock/simple-cicd:staging
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-cicd-staging-service
spec:
  selector:
    app: simple-cicd-staging
  ports:
    - protocol: TCP
      port: 80  # Porta do Service
      targetPort: 8080  # Porta do container
  type: LoadBalancer # Caso queira expor para fora do cluster, pode ser LoadBalancer ou NodePort
